version: '3'

services:
  server:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    build: ./api-module
    container_name: server
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs  # 로그 파일을 저장할 볼륨 추가