version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: flow
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: flowserver123
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  server:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    build: ./api-module
    container_name: server
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs  # 로그 파일을 저장할 볼륨 추가