version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: flow
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: flowserver123
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci