spring:
  profiles:
    include:
      - dev
      - prod

---

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info